### PR TITLE
feat: batch operations

### PR DESCRIPTION
**Pull request by erakli**

### CODE REVIEW

**Comment by erakli** [comment]
@dgilman take a look on this PR, please

**Comment by dgilman** [comment]
Thank you for the PR!

Accurate rate limiting is an important gspread_asyncio feature. The gspread implementations of add_protected_range and insert_rows do two API calls and the current rate limiting system in gspread_asyncio (the delay() method) assumes that a single gspread call only does one API call. Those two functions can't be merged in. The other ones look good, though.

TODO:

- [ ] Replace add_protected_range and insert_rows with a `raise NotImplemented('does two network calls, may be implemented later')`
- [ ] Bump the minimum required version of gspread to 3.4 in setup.py (for append_rows).
- [ ] Put a `.. versionadded:: 1.1` in the docstrings for the rest of the APIs
- [ ] (Optional) Be a good citizen and open a PR to gspread to add `.. versionadded` to a few of their docstrings (they missed a few with these new functions, read their changelog to find out which ones)

**Comment by erakli** [comment]
> Replace add_protected_range and insert_rows with a raise NotImplemented('does two network calls, may be implemented later')

I needed `add_protected_range()` method in my code, so I decided to adopt code from `gspread` to this package. I don't have enough time to make PR in original library (because it is changes in API) and mirror changes here.

`insert_rows()` is now marked as not implemented.

> Bump the minimum required version of gspread to 3.4 in setup.py (for append_rows).

Done. Also, I changed package version to explicit `1.1.0` string because this package could not be installed from git directly. I had problems with `version_tag` file which need to be generated through Makefile. It's not obvious and commonly used practice in python packages.

> Put a .. versionadded:: 1.1 in the docstrings for the rest of the APIs

Done.

> (Optional) Be a good citizen and open a PR to gspread to add .. versionadded to a few of their docstrings (they missed a few with these new functions, read their changelog to find out which ones)

Sorry, I have no time for this. Also, I think this repo need to be refactored to meet PEP.

**Comment by dgilman** [comment]
> I needed `add_protected_range()` method in my code, so I decided to adopt code from `gspread` to this package. I don't have enough time to make PR in original library (because it is changes in API) and mirror changes here.

Thinking about this a bit more: maybe I shouldn't be so afraid of multiple API call methods. How about I add a new kwarg to `_call` that passes back the number of API calls that gspread does for a method, and I just call `delay()` that number of times. I respect that you're busy here, sorry for having you run around and delete some stuff, I will hack this in myself.

So what I'll do here: I'll grab your branch, merge it in without any of the NotImplemented(), make those changes and hopefully get a release out tonight. I was looking at it last night and there are a few low hanging things I should clean up here. I'll close this PR when that release is ready.

> Also, this package could not be installed from git directly. I had problems with `version_tag` file which need to be generated through Makefile. It's not obvious and commonly used practice in python packages. My advice is to switch to something more pip friendly.

I think pulling the version number from the git tag is an excellent practice and more people should do it! But, it does break git installs unnecessarily. I can do a quick PR to put in a default version for those cases.

**Comment by dgilman** [comment]
Version 1.1 is released with the five APIs. Thanks for your contribution! If there is anything else you'd like to have note that I ran the codebase through Black, so you may have merge conflicts.

**Pull request closed without merging**
